### ISSUE TITLE
Can't find init.js under windows

### ISSUE THREAD

**Issue by banxian** [siara-cc/sqlite3_page_explorer#21]
platform: windows 10, ltsb
screen resolution: 1920*1200
use build on release page.
after unzip sqlite3-page-explorer.zip
double click sqlite3-page-explorer.exe on explorer, nothing happened.
launch from commandline show an error like this:

internal/modules/cjs/loader.js:604
    throw err;
    ^

Error: Cannot find module 'T:\Apps\sqlite3-page-explorer\resources\electron.asar\browser\init.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:602:15)
    at Function.Module._load (internal/modules/cjs/loader.js:528:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:753:10)
    at startup (internal/bootstrap/node.js:241:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:579:3)

**Comment by siara-cc** [comment]
Hi, the release I made is quite old and probably thats why.
There have been a lot of security updates with Electron since then.
I will try to make a new release, but in the meanwhile if you would like to try this out, you could just install electron and invoke it with `electron .` in the home folder.  I have not tried it with Windows but should work. if not please let me know.

**Comment by banxian** [comment]
Hello, thanks for reply.
I installed electron in node.js(18.16) and launched with electron . with master branch.
the UI shows up, but when I open a example db, it popup "ReferenceError: $ is not defined" error.
the example db I used is chinook.db from sqlitetutorial.net, and some db generate by tencent/alibaba's IM software.

**Comment by siara-cc** [comment]
Hi, Please pull master branch and try again.  Alternatively I guess it would also work if you did `npm install` and `npm update` on the home folder.
I added the Jquery dependency manually instead of relying on the one in `node_modules` folder.  Now with this change I think there is no need for `npm`.
I don't have Windows but I guess it should work now.  If not I will have to install Windows and check!

**Comment by banxian** [comment]
okay, it's works now. another suggestion: "file change counter" and "version-valid-for" should display as unsigned integer instead of negative number.
